
spring:
  ai:
    vectorstore:
      milvus:
        host: localhost  # Milvus服务地址
        port: 19530       # 默认端口
        collection-name: doc_chunks  # 存储文档片段的集合名
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        model: qwen-turbo  # 通义千问模型名称（核心配置）

server:
  port: 8080

# enabled debug log out.
logging:
  level:
    org.springframework.ai: debug
    com.alibaba.dashscope.api: debug
    com.alibaba.cloud.ai.dashscope.chat: debug